services:
  web:
    build: .
    # image: php:8.2-apache
    container_name: exametrika_web
    ports:
      - "${WEB_PORT:-8080}:80"
    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: exametrika_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT:-55433}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/002-seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data: